package com.wzh.demo.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2019-03-31T19:54:58.255+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://service.webservice.demo.wzh.com/", name = "IhelloService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IhelloService {

    @WebResult(name = "return", targetNamespace = "http://service.webservice.demo.wzh.com/", partName = "return")
    @WebMethod
    public java.lang.String helloWebService(
        @WebParam(partName = "msg", name = "msg")
        java.lang.String msg
    );
}
